-- Harvest & Pack Sheet public-link token (#195, idea PR #194).
--
-- Single-row table holding the secret token for the public /f/[token]
-- fulfillment report. Admin-only RLS: the public route reads it via the
-- service-role client (which bypasses RLS), exactly like customer token
-- lookup. Deliberately NOT stored on ordering_schedule — that table carries
-- an anon-read policy (public_read_ordering_schedule) so the customer page
-- can read is_open, and RLS is row-level, not column-level: a token column
-- there would be readable by anyone holding the public anon key.

create table public.fulfillment_link (
  id uuid primary key default gen_random_uuid(),
  token uuid not null unique default gen_random_uuid(),
  is_singleton boolean not null default true unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint fulfillment_link_singleton check (is_singleton)
);

comment on table public.fulfillment_link is
  'Singleton holding the secret token for the public /f/[token] harvest & pack sheet. Admin-only RLS; public route reads via service role.';

alter table public.fulfillment_link enable row level security;

-- Admin (authenticated) full CRUD — supports a future "Regenerate link" action.
create policy "admin_all_fulfillment_link" on public.fulfillment_link
  for all to authenticated using (true) with check (true);

-- No anon policy: anon has zero access to this table.

-- Seed the single row (token auto-generated by the column default).
insert into public.fulfillment_link (is_singleton) values (true)
  on conflict (is_singleton) do nothing;
